### ISSUE TITLE
Cannot uninstall Device Setup application

### ISSUE THREAD

**Issue by dolsen01** [samolego/Canta#104]
Hello;

I try to uninstall Device Setup as a work around for a Verizon phone I have that cannot be unlocked, when I uninstall it though, it disappears from the list, just to not be uninstalled. 

**Version info**
 - Android version: 15
 - Canta version: latest
 - Shizuku version: latest

**Logcat**

<details>
  <summary>View logcat</summary>
  ```logcat
  paste logcat here
  ```
</details>

**Comment by samolego** [comment]
Please include the actual versions and the logcat.

**Comment by dolsen01** [comment]
Shizuku version: 13.5.4.r1049.0e53409
Canta Version: v1.4.1
Android Version: 15
Android Build Number: AP3A 241005.015
Android Security Update: October 5th, 2024

I am not sure how to capture the logcat files, is this stored somewhere? I was using adb from my PC since I'm trying to keep the device totally offline for the time being. Thanks.

**Comment by dolsen01** [comment]
10-20 10:08:23.339  2104  2124 I deeptouch: I0000 00:00:1729433303.339620    2124 tf_lite_classifier.cc:413] Event stream classified as kNone
10-20 10:08:23.343 14408 14452 I Canta   : Uninstalling 'com.google.android.apps.work.oobconfig'
10-20 10:08:23.345   958   958 D audioserver: logFgsApiBegin: FGS Logger Transaction failed, -129
10-20 10:08:23.345  1416  9984 W AS.PlaybackActivityMon: No piid assigned for invalid/internal port id 37
10-20 10:08:23.345 14408 14452 W JavaBinder: ibinderForJavaObject: 0x73bbef0d20 is not a Binder object
10-20 10:08:23.345 14408 14452 E Parcel  : Native binder in markForBinder is null for non-null jobject
10-20 10:08:23.345  6481  6728 D Service : transact: uid=10280, descriptor=android.content.pm.IPackageManager, code=137
10-20 10:08:23.346 14408 14452 I Canta   : Uninstalling 'com.google.android.apps.work.oobconfig' [system: true]
10-20 10:08:23.347 14408 14452 W JavaBinder: ibinderForJavaObject: 0x73bbef0610 is not a Binder object
10-20 10:08:23.347 14408 14452 E Parcel  : Native binder in markForBinder is null for non-null jobject
10-20 10:08:23.347  6481  6728 D Service : transact: uid=10280, descriptor=android.content.pm.IPackageInstaller, code=12
10-20 10:08:23.348  1416  1572 W PackageManager: Attempted to delete protected package: com.google.android.apps.work.oobconfig
10-20 10:08:23.353   881   913 D audio_hw_output_stream: update stream 1 active 1 gain 0.040352
10-20 10:08:23.505   958  1738 D audioserver: logFgsApiEnd: FGS Logger Transaction failed, -129
10-20 10:08:23.506   881   913 W amcs_ext_file: update_third_party_effect_amcs_data:fail to send ioctl amcs, ret -1
10-20 10:08:23.506   881   913 W audio_hw: fail on interact with audio_amcs_ext.so -1
10-20 10:08:23.506   881   913 D audio_hw_waves: update_sink_info_from_usecases: update amcs, instance id 1, volume 152 0 0 0 0 0 0 0 0 0
10-20 10:08:23.506   881   913 D audio_hw_output_stream: update stream 1 active 0 gain 0.000000
10-20 10:08:24.141  1187  1187 D AOC     : F1:[Idle Tracker] long no idle:[0] average between idle:[0.075775ms] max no idle:[19.502402ms]
10-20 10:08:24.306 11035 11035 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.mdd.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
10-20 10:08:25.141  1187  1187 D AOC     : F1:[Idle Tracker] long no idle:[0] average between idle:[0.075847ms] max no idle:[19.502402ms]
10-20 10:08:26.141  1187  1187 D AOC     : F1:[Idle Tracker] long no idle:[0] average between idle:[0.075919ms] max no idle:[19.502402ms]

I believe I got the logcat file, please let me know if there is any more information you need. Thank you!

**Comment by samolego** [comment]
Please use canta version from github, fdroid one is really old.

**Comment by dolsen01** [comment]
Used Canta version 2.2.1, this is what I got when I attempted to uninstall:

10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo: Exception when checking for satellite support. Assuming it is not supported for this device.
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo: android.telephony.satellite.SatelliteManager$SatelliteException
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at android.telephony.satellite.SatelliteManager$5.lambda$onReceiveResult$4(SatelliteManager.java:786)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at android.telephony.satellite.SatelliteManager$5$$ExternalSyntheticLambda0.runOrThrow(D8$$SyntheticClass:0)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at android.os.Binder.withCleanCallingIdentity(Binder.java:550)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at android.telephony.satellite.SatelliteManager$5.lambda$onReceiveResult$5(SatelliteManager.java:785)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at android.telephony.satellite.SatelliteManager$5$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-20 13:12:25.127  2043  2101 E DeviceBasedSatelliteRepo:      at java.lang.Thread.run(Thread.java:1012)
10-20 13:12:25.398  1157  1157 D AOC     : A3:MSG: usf_vsc_log.cc, 53: USF: [WO] Rejected by settle_time and gyro finds no rotation 0
10-20 13:12:25.728  2177  2197 I deeptouch: I0000 00:00:1729444345.728506    2197 tf_lite_classifier.cc:413] Event stream classified as kNone
10-20 13:12:25.730  1354  2347 W ActivityManager: pid 6351 org.samo_lego.canta sent binder code 1599296841 with flags 2 to frozen apps and got error -74
10-20 13:12:25.731  6351  6351 I i       : Shizuku permission result: 0, sui status: false
10-20 13:12:25.733  6351  6351 W JavaBinder: ibinderForJavaObject: 0x7fe76caf00 is not a Binder object
10-20 13:12:25.733  6351  6351 E Parcel  : Native binder in markForBinder is null for non-null jobject
10-20 13:12:25.733  6338  6364 D Service : transact: uid=10282, descriptor=android.content.pm.IPackageManager, code=137
10-20 13:12:25.734  6351  6351 I Canta   : Uninstalling 'com.google.android.apps.work.oobconfig' [system: true]
10-20 13:12:25.735  6351  6351 W JavaBinder: ibinderForJavaObject: 0x7fe76cabf0 is not a Binder object
10-20 13:12:25.735  6351  6351 E Parcel  : Native binder in markForBinder is null for non-null jobject
10-20 13:12:25.735  6338  6364 D Service : transact: uid=10282, descriptor=android.content.pm.IPackageInstaller, code=12
10-20 13:12:25.737  1354  1585 W PackageManager: Attempted to delete protected package: com.google.android.apps.work.oobconfig
10-20 13:12:25.743  6351  6351 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=false callback=b.x@9e61ed0
10-20 13:12:25.743  1354  2347 D CoreBackPreview: Window{6111ad1 u0 org.samo_lego.canta/org.samo_lego.canta.MainActivity}: Setting back callback null
10-20 13:12:25.745  6351  6385 D HWUI    : endAllActiveAnimators on 0xb4000074afcec870 (B) with handle 0xb4000073ffcd1f70
10-20 13:12:25.746  1354  2347 W InputManager-JNI: Input channel object '6111ad1 org.samo_lego.canta/org.samo_lego.canta.MainActivity (client)' was disposed without first being removed with the input manager!
10-20 13:12:25.759  1354  1504 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
10-20 13:12:25.768  1354  1898 I ImeTracker: org.samo_lego.canta:5e8d4bab: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
10-20 13:12:25.769  1354  1898 I ImeTracker: org.samo_lego.canta:5e8d4bab: onCancelled at PHASE_SERVER_SHOULD_HIDE
10-20 13:12:25.771  4318  4318 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3157
10-20 13:12:25.772  4318  4318 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2248 repeatCheckTimes = 0, locked = false
10-20 13:12:25.772  4318  4318 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1986 onStartInput(EditorInfo{EditorInfo{packageName=org.samo_lego.canta, inputType=28001, inputTypeString=Normal, enableLearning=true, autoCorrection=true, autoComplete=true, imeOptions=2000003, privateImeOptions=null, actionName=SEARCH, actionLabel=null, initialSelStart=0, initialSelEnd=0, initialCapsMode=0, label=null, fieldId=-1, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
10-20 13:12:25.773  4318  4318 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2248 repeatCheckTimes = 1, locked = false
10-20 13:12:25.774  4318  4318 I AndroidIME: InputBundleManager.loadActiveInputBundleId():450 loadActiveInputBundleId: en-US, ime_english_united_states
10-20 13:12:25.774  1354  2347 W PackageConfigPersister: App-specific configuration not found for packageName: org.samo_lego.canta and userId: 0
10-20 13:12:25.833   892   921 I CHRE    : @  69.991: [AR] walking: 79.607844
10-20 13:12:26.197  2277  3278 D HbmSvManager: Ambient sensor :  TMD3719 Ambient Light update Lux : 84.34947
10-20 13:12:26.655   935  1541 I suez-nanoapp-clients: Barometric peak detected: magnitude = 0.100729 hPa (bucket: 2), duration = 40.000000 ms (bucket: 3).
10-20 13:12:26.657   935  1541 I suez-nanoapp-clients: Vendor atom [id = 100047] reported.
10-20 13:12:26.662   935  1541 I suez-nanoapp-clients: Barometric peak detected: magnitude = 0.103624 hPa (bucket: 2), duration = 40.000000 ms (bucket: 3).
10-20 13:12:26.662   935  1541 I suez-nanoapp-clients: Vendor atom [id = 100047] reported.
10-20 13:12:26.663   935  1541 I suez-nanoapp-clients: Barometric peak detected: magnitude = 0.126920 hPa (bucket: 3), duration = 80.000000 ms (bucket: 7).
10-20 13:12:26.663   935  1541 I suez-nanoapp-clients: Vendor atom [id = 100047] reported.
10-20 13:12:26.664   892   921 I CHRE    : @  70.811: [ip] Peak detected: magnitude = 0.100729 hpa, duration = 40.000000 ms
10-20 13:12:26.664   935  1541 I suez-nanoapp-clients: Barometric peak detected: magnitude = 0.104008 hPa (bucket: 2), duration = 40.000000 ms (bucket: 3).
10-20 13:12:26.665   935  1541 I suez-nanoapp-clients: Vendor atom [id = 100047] reported.
10-20 13:12:26.666   892   921 I CHRE    : @  70.813: [ip] Peak detected: magnitude = 0.103624 hpa, duration = 40.000000 ms
10-20 13:12:26.666   892   921 I CHRE    : @  70.814: [ip] Peak detected: magnitude = 0.126920 hpa, duration = 80.000001 ms
10-20 13:12:26.666   892   921 I CHRE    : @  70.814: [ip] Peak detected: magnitude = 0.104008 hpa, duration = 40.000000 ms
10-20 13:12:27.153  2523  4131 W gcfj    : [{0}] Failed to resolve name. status={1}
10-20 13:12:27.162   558   558 D DisplayModeController: setDesiredMode 4619827677550801152 {mode={fps=60.00 Hz, modePtr={id=3, vsyncRate=60.00 Hz, peakRefreshRate=60.00 Hz}}, emitEvent=true, force=false}
10-20 13:12:27.163   561   601 D hwc-display: setActiveConfigWithConstraints:: PrimaryDisplay config(39) test(0)
10-20 13:12:27.163   561   601 I hwc-display: [PrimaryDisplay] setActiveConfigWithConstraints: config(39)
10-20 13:12:27.164   561   601 D hwc-drm-connector: Updating LP mode to: 1080x2340x30
10-20 13:12:27.165  1354  1504 I DisplayDeviceRepository: Display device changed render timings: "Built-in Screen", renderFrameRate=60.000004, presentationDeadlineNanos=11500000, appVsyncOffsetNanos=6233334
10-20 13:12:27.168  1354  1571 D BrightnessThermalClamper: Thermal status observer already started
10-20 13:12:27.170   886   918 D audio_hw: adev_set_parameters: enter: screen_state=on
10-20 13:12:27.170  1354  1504 D DisplayManagerService: Ignore redundant display event 0/2 to 10213/6039
10-20 13:12:27.170  1354  1504 D DisplayManagerService: Ignore redundant display event 0/2 to 10281/6216
10-20 13:12:27.423  1354  1921 E WifiScoringParams: Invalid frequency(-1), using 5G as default rssi array
10-20 13:12:27.438  1106  1106 W wificond: Failed to get NL80211_ATTR_MAX_NUM_AKM_SUITES
10-20 13:12:27.445  1106  1106 W wificond: Failed to get NL80211_ATTR_MAX_NUM_AKM_SUITES
10-20 13:12:27.450  1106  1106 W wificond: Failed to get NL80211_ATTR_MAX_NUM_AKM_SUITES
10-20 13:12:27.456  1106  1106 W wificond: Failed to get NL80211_ATTR_MAX_NUM_AKM_SUITES
10-20 13:12:27.483  1354  2302 I DeviceLockControllerConnectorImpl: Unbinding DeviceLockControllerService
10-20 13:12:27.483  1354  2302 I DeviceLockControllerConnectorImpl: Unbinding com.google.android.devicelockcontroller/com.android.devicelockcontroller.DeviceLockControllerService
10-20 13:12:27.492  1354  2302 D CompatChangeReporter: Compat change id reported: 311208629; UID 10259; state: ENABLED
10-20 13:12:27.501  6338  6364 D BinderSender: onUidCachedChanged: uid=10259, cached=true
10-20 13:12:27.564  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET, states=14
10-20 13:12:27.570  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET6, states=14
10-20 13:12:27.571  1354  1932 D InetDiagMessage: Destroyed live tcp sockets for uids={10281} in 15ms
10-20 13:12:27.576  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET, states=14
10-20 13:12:27.584  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET6, states=14
10-20 13:12:27.584  1354  1932 D InetDiagMessage: Destroyed live tcp sockets for uids={20281} in 13ms
10-20 13:12:27.876  1354  1875 D ActivityManager: freezing 2436 com.android.settings
10-20 13:12:27.878  1354  1875 D ActivityManager: freezing 4800 com.google.android.settings.intelligence
10-20 13:12:27.894  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET, states=14
10-20 13:12:27.899  1354  1932 D InetDiagMessage: Destroyed 0 sockets, proto=IPPROTO_TCP, family=AF_INET6, states=14
10-20 13:12:27.899  1354  1932 D InetDiagMessage: Destroyed live tcp sockets for uids={10168} in 16ms
10-20 13:12:29.000  1354  1531 D OomAdjuster: Not killing cached processes
10-20 13:12:29.008  6338  6364 D BinderSender: onUidCachedChanged: uid=10137, cached=true
10-20 13:12:29.066  2809  3497 I BistoHotwordHelper: (REDACTED) getHotwordActive::active query: %s, watch: %s, devices connected: %s
10-20 13:12:29.455  6338  6364 D BinderSender: onUidIdle: uid=10162, disabled=false
10-20 13:12:29.456  6338  6364 V BinderSender: Uid 10162 starts
10-20 13:12:29.456  6338  6364 D BinderSender: sendBinder to uid 10162: packages=com.android.sdm.plugins.connmo
10-20 13:12:29.459  1157  1157 D AOC     : A3:MSG: usf_vsc_log.cc, 53: USF: [WO] Rejected by settle_time and gyro finds no rotation 0
10-20 13:12:29.479  2043  2043 D DLObserver: onReceive(); android.intent.action.BATTERY_CHANGED
10-20 13:12:29.479  2043  2043 D DLObserver: plugged=2
10-20 13:12:29.483  2043  2043 I ReverseChargingControl: handleIntentForReverseCharging(): rtx=0 wlc=0 plgac=0 ac=0 acrtx=0 extra=2 this=com.google.android.systemui.reversecharging.ReverseChargingController@398c685
10-20 13:12:29.483  2043  2043 D SystemEventDataSource: onReceive: intentAction
10-20 13:12:29.485  2043  2043 D PowerNotificationWarningsGoogleImpl: onReceive: android.intent.action.BATTERY_CHANGED
10-20 13:12:29.485  2043  2043 D IncompatibleChargerNotification: dispatchIntent: android.intent.action.BATTERY_CHANGED
10-20 13:12:29.485  2043  2120 D GoogleBatteryDataSource: fetchDwellDefendStatus: CONNECTED
10-20 13:12:29.485  2043  2120 D GoogleBatteryDataSource: fetchTempDefendStatus: t_sum=0, time_sum=0 t_avg=0 lst_v=4371406 lst_t=259 lst_u=48, dt=0, t=0 e=1
10-20 13:12:29.486  2043  2120 D SystemEventDataSource: updatedEventData: SystemEventData(intentAction=android.intent.action.BATTERY_CHANGED, plugged=EventData(value=2), batteryScale=EventData(value=100), batteryLevel=EventData(value=100), chargingStatus=EventData(value=1), maxChargingCurrent=EventData(value=500000), maxChargingVoltage=EventData(value=5000000), batteryStatus=EventData(value=2), halEventData=HalEventData(dockDefendStatus=EventData(value=-3), tempDefendEventData=EventData(value=false), dwellDefendEventData=EventData(value=false)), settingsEventData=SettingsEventData(dockDefenderBypass=EventData(value=0), chargingLimitSettings=EventData(value=0)), frameworkApiEventData=FrameworkApiEventData(batterySaverState=EventData(value=false), extremeBatterySaverState=EventData(value=false)))
10-20 13:12:29.486  2043  2120 D SystemEventDataSource: extra doesn't changed, no need to onEventSourceUpdate
10-20 13:12:29.491  6338  6364 D BinderSender: onUidCachedChanged: uid=10137, cached=false
10-20 13:12:29.491  6338  6364 V BinderSender: Uid 10137 already starts
10-20 13:12:29.492  2043  6468 D PowerUI : can't show warning due to - plugged: true status unknown: false
10-20 13:12:30.570  1354  2347 D WifiNl80211Manager: Scan result ready event
10-20 13:12:30.571  1354  2347 D WifiNative: Scan result ready event
10-20 13:12:30.588  1354  1921 I WifiCountryCode: Skip framework CC update because it is empty
10-20 13:12:30.589   966  1027 I WifiHAL : Creating message to get link statistics; iface = 47
10-20 13:12:30.647  6338  6364 D BinderSender: onUidIdle: uid=10228, disabled=false
10-20 13:12:30.648  6338  6364 V BinderSender: Uid 10228 starts
10-20 13:12:30.649  6338  6364 D BinderSender: sendBinder to uid 10228: packages=com.google.android.carriersetup
10-20 13:12:30.673   966  2614 D WifiHAL : Start debug command: mType GET_FEATURE
10-20 13:12:30.673   966  2614 I WifiHAL : CreateRequest mType = GET_FEATURE
10-20 13:12:30.673   966  2614 D WifiHAL : In DebugCommand::handleResponse, mType:GET_FEATURE
10-20 13:12:30.673   966  2614 D WifiHAL : len = 4, expected len = 4

**Comment by dolsen01** [comment]
Attempting to uninstall oobconfig specifically.

**Comment by samolego** [comment]
ic, i don't really know why it doesn't work rn, sorry.

**Comment by dolsen01** [comment]
Is there any reason it shouldn't be able to uninstall? It says it's protected but ideally this should still be able to uninstalled right? It's a Google Pixel 7 Pro

**Comment by samolego** [comment]
I don't see any specific reason ...
