### ISSUE TITLE
[BUG] App crashes if SUI permission isn't granted

### ISSUE THREAD

**Issue by NikunjKhangwal** [samolego/Canta#98]
If SUI permission isn't granted the app crashes after selecting any app and hitting uninstall button. It doesn't ask for SUI permission.

Log:
`FATAL EXCEPTION: main
Process: org.samo_lego.canta, PID: 32336
java.lang.SecurityException: Permission Denial: transactRemote from pid=32336 requires permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInstaller(IPackageManager.java:7378)
	at D2.l.a(Unknown Source:13)
	at w2.a.k(Unknown Source:106)
	at J0.h.k(Unknown Source:253)
	at y2.k.u(Unknown Source:282)
	at I1.a.o(Unknown Source:8)
	at W1.E.run(Unknown Source:114)
	at n0.T.K(Unknown Source:23)
	at n0.S.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
	Suppressed: b2.f: [n0.r0@867dc42, G.g@6611453, o0{Cancelling}@6b92190, T@a6d5a89]`

**Comment by samolego** [comment]
Thanks for reporting.

**Comment by mayanksharma-dev** [comment]
It looks like a permission error or some security settings might be causing this (not 100% sure what exactly causes that), but it might be blocking the app to perform those operations. 

You may try these steps in order to check whether it's fixed or not?
The below devices (somewhat related way for each device, not sure whether these are the exact settings name):

#### For Xiaomi / HyperOS / POCO
The phone has an extra "gatekeeper" you need to unlock.
1. Go to **Settings** > **Additional Settings** > **Developer Options**.
2. Look for **USB Debugging (Security Settings)**.
3. Turn it **ON**.
   * **Note:** You'll see a few warnings—just wait for the timer and hit "Accept." This is what allows Canta to work its magic.
4. Restart the Shizuku app, and you're good to go!

#### For Realme / OPPO / Vivo
These phones have a "monitoring" feature that gets in the way.
1. Go to your **Developer Options**.
2. Scroll all the way to the bottom.
3. Find **Disable permission monitoring** and turn it **ON**.
4. Close Canta (swipe it away from your recent apps) and open it up.

#### For Samsung (One UI)
Samsung's "Auto Blocker" can sometimes be too strict.
1. Go to **Settings** > **Security and Privacy**.
2. If **Auto Blocker** is on, try turning it **OFF** while you use Canta.
3. You can turn it back on as soon as you're done cleaning up (debloating) your apps.


#### Or you could also try these:

    Turn off the Scan: Try turning OFF "Verify apps over USB" (or something like it). This stops the phone from over-scanning Canta’s actions.

    The "Wireless" Trick: Try using "Wireless Debugging" inside the Shizuku app instead of a cable. Some newer Vivo models (and others) only give full permission through Wi-Fi debugging.

**Comment by NikunjK8** [comment]
I'm on AOSP, not any manufacturer's android skin. It seems like Canta was designed with Shizuku in mind and SUI implementation is incomplete. It could also be upstream issue since SUI isn't actively being worked on.

**Comment by MajliTech** [comment]
For anyone that might need this:
You will need to manually allow Canta in Sui. To do this, you need to:
1. Open up your dialer and type in `*#*#784784#*#*` | ***OR***  | Open up Developer Settings, add the suggested tile to your home screen and open it
2. Wait for the app list to load
3. Find Canta and select *Allowed* upon pressing on it
After that, Canta worked for me as usual.
